service: aws-lambda-dynamodb
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:900201653604:table/TaskTable

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get

  addTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
  
  deleteTask:
    handler: src/deleteTask.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete
  
  getTaskList:
    handler: src/getTaskList.getTaskList
    events:
      - httpApi:
          path: /tasks
          method: get

  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: get

  editTask:
    handler: src/editTask.editTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: put

resources:
  Resources:
    TaskTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "TaskTable"
        BillingMode: "PAY_PER_REQUEST"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
